### ISSUE TITLE
Enhancement: Update Actions Secret `WEBHOOK_URL` to an IndexerDAO webhook URL

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/goerli-eth-monitor#2]
Currently using a test webhook URL on my development Discord Server. 

We need to generate a new webhook URL in IndexerDAO Server. 

May also need to create a channel first so we don't spam an existing channel with these reports.

**Comment by Web3Slimchance** [comment]
- Added a new discord channel. 
- Added the webhook url to `WEBHOOK_URL`
